CREATE TABLE llx_lmdbsalescommissions_line
(
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_user integer NOT NULL,
	fk_soc integer DEFAULT NULL,
	source_type varchar(32) DEFAULT 'proposal' NOT NULL,
	fk_source integer NOT NULL,
	source_ref varchar(128) DEFAULT NULL,
	mode varchar(32) NOT NULL,
	amount_base double(24,8) DEFAULT 0 NOT NULL,
	margin_base double(24,8) DEFAULT NULL,
	rate double(10,4) DEFAULT NULL,
	fk_tier integer DEFAULT NULL,
	commission_total double(24,8) DEFAULT 0 NOT NULL,
	payable_total double(24,8) DEFAULT 0 NOT NULL,
	paid_total double(24,8) DEFAULT 0 NOT NULL,
	status smallint DEFAULT 0 NOT NULL,
	date_acquired datetime DEFAULT NULL,
	fk_rule integer DEFAULT NULL,
	fk_payment_term integer DEFAULT NULL,
	fk_proposal_dispatch integer DEFAULT NULL,
	rule_source varchar(32) DEFAULT NULL,
	snapshot_rule_label varchar(255) DEFAULT NULL,
	snapshot_rule_rate double(10,4) DEFAULT NULL,
	snapshot_base_type varchar(16) DEFAULT NULL,
	snapshot_value_type varchar(16) DEFAULT NULL,
	snapshot_value double(24,8) DEFAULT NULL,
	note_private text,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer DEFAULT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14)
) ENGINE=innodb;
